# Generated by Django 4.2.1 on 2023-12-05 07:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0002_datasource_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID of the data source')),
                ('labels', models.JSONField(default=dict, help_text='Labels for the data source')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Time when the data source was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when the data source was updated')),
                ('data_source', models.ForeignKey(help_text='Data source', on_delete=django.db.models.deletion.CASCADE, to='datasources.datasource')),
            ],
        ),
    ]
