# Generated by Django 4.2.1 on 2023-12-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0003_datasourcelabels'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcelabels',
            name='data_source_name',
            field=models.CharField(blank=True, help_text='Name of the data source', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datasourcelabels',
            name='labels_name',
            field=models.CharField(blank=True, help_text='Name of the data source labels', max_length=100, null=True),
        ),
    ]
