# Generated by Django 4.2.1 on 2023-12-05 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasources', '0004_datasourcelabels_data_source_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcelabels',
            name='owner',
            field=models.ForeignKey(default=22, help_text='Owner of the data source labels', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
