# Generated by Django 4.2.1 on 2023-12-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0005_datasourcelabels_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcelabels',
            name='variables',
            field=models.JSONField(blank=True, default=dict, help_text='Variables for the data source', null=True),
        ),
    ]
